# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53bd734c2f90cf971b829cfa01e8b018970528359fddbff62a3b9c12445e7a6a09113444d092ae41efa87fc8b67f1d86d2f584b1e0f304214c8271a29fd7bea7

test:
  secret_key_base: efd99ef0c0aef2bea694dd68ff1ecece33a6456fd9899c38cf8c5c4273b95978fa0873116eb71d66d245ab63951a24a57bfb3f487f2e5c9bca5921da2e7db14a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
